### ISSUE TITLE
Add GitHub Actions as CI

### ISSUE THREAD

**Issue by szabgab** [PerlServices/OPM-Maker-Command-depcheck#1]
Hi Renee,

As you might know I am using the CPAN Digger to locate recently release modules that don't have a CI system. As I can see [some of your modules](https://cpan-digger.perlmaven.com/author/PERLSRVDE) have a CI setup, but most don't.

I've written about CI and GitHub Actions [here](https://perlmaven.com/github-actions).

If you are interested I'd be happy to send you PR to this and to your other CPAN modules.

**Comment by reneeb** [comment]
Yeah, go ahead ;-) Thank you Gabor!
